name: Build document
on:
  push:
    branches:
      - doc

jobs:
  # 缓存
  cache:
    name: Cache node_modules
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !cancelled()}}
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          # install depenecies...
          yarn install
  # 构建
  build:
    name: Build app
    runs-on: ubuntu-latest
    needs: cache
    if: ${{ !cancelled() }}
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
          fail-on-cache-miss: true
      - name: Build
        run: |
          yarn build
        env:
          STATIC_PATH: '/'
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages-${{ github.run_number }}
          path: dist
          retention-days: 1
  # 部署
  deploy:
    name: Deploy to github pages
    runs-on: ubuntu-latest
    needs: build
    if: ${{ ! failure() }}
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-${{ github.run_number }}
